/*
 * Setting buttons view - flash, frame rate, delay photo, etc.
 */

import { camera } from '@kit.CameraKit';
import { AVRecorderState } from '../cameramanagers/VideoManager';
import { showToast } from '../camerautils/CommonUtil';
import PreviewViewModel from '../cameramodels/PreviewViewModel';
import { AppTheme } from '../common/constants/Theme';

interface FlashItem {
  mode: camera.FlashMode;
  image: Resource;
  title: ResourceStr;
  toast: ResourceStr;
}

/**
 * Set up button components, configure the flash, preview frame rates, and other features.
 */
@Component
struct SettingButtonsView {
  @State flashMode: camera.FlashMode = camera.FlashMode.FLASH_MODE_CLOSE;
  @ObjectLink previewVM: PreviewViewModel;
  private flashItems: FlashItem[] = [
    {
      mode: camera.FlashMode.FLASH_MODE_CLOSE,
      image: $r('sys.symbol.camera_flash_slash'),
      title: 'off',
      toast: $r('app.string.flash_close')
    },
    {
      mode: camera.FlashMode.FLASH_MODE_OPEN,
      image: $r('sys.symbol.camera_flash'),
      title: 'on',
      toast: $r('app.string.flash_open')
    },
    {
      mode: camera.FlashMode.FLASH_MODE_AUTO,
      image: $r('sys.symbol.camera_flash_auto'),
      title: 'auto',
      toast: $r('app.string.flash_auto')
    },
    {
      mode: camera.FlashMode.FLASH_MODE_ALWAYS_OPEN,
      image: $r('sys.symbol.lightbulb_1'),
      title: 'always_on',
      toast: $r('app.string.flash_always')
    }
  ];
  private photoFlashModes: camera.FlashMode[] = [
    camera.FlashMode.FLASH_MODE_CLOSE,
    camera.FlashMode.FLASH_MODE_OPEN,
    camera.FlashMode.FLASH_MODE_AUTO,
    camera.FlashMode.FLASH_MODE_ALWAYS_OPEN
  ];
  private videoFlashModes: camera.FlashMode[] = [
    camera.FlashMode.FLASH_MODE_CLOSE,
    camera.FlashMode.FLASH_MODE_ALWAYS_OPEN
  ];

  getFlashItem(mode: camera.FlashMode): FlashItem | undefined {
    return this.flashItems.find(item => item.mode === mode);
  }

  @Builder
  flashButton(flashModes: camera.FlashMode[]) {
    SymbolGlyph(this.getFlashItem(this.flashMode)?.image)
      .fontSize(22)
      .fontColor([AppTheme.TEXT_PRIMARY])
      .bindMenu(flashModes.map(mode => {
        const flashItem = this.getFlashItem(mode)!;
        const menuElement: MenuElement = {
          value: flashItem.title,
          action: () => {
            this.flashMode = mode!;
            this.previewVM.setCameraFlashMode(mode);
            showToast(this.getUIContext(), flashItem.toast);
          }
        };
        return menuElement;
      }))
  }

  @Builder
  videoTimerBuilder() {
    if (this.previewVM.isVideoRecording()) {
      Row({ space: 5 }) {
        SymbolGlyph(this.previewVM.checkVideoState(AVRecorderState.STARTED) ? $r('sys.symbol.record_circle') :
          $r('sys.symbol.pause'))
          .fontSize(22)
          .fontColor(this.previewVM.checkVideoState(AVRecorderState.STARTED) ? [Color.Red, 'rgba(255,0,0,0)'] :
            [AppTheme.TEXT_PRIMARY])
          .renderingStrategy(SymbolRenderingStrategy.MULTIPLE_COLOR)
        Text(this.previewVM.checkVideoState(AVRecorderState.STARTED) ? $r('app.string.recording') :
          $r('app.string.paused'))
          .fontColor(AppTheme.TEXT_PRIMARY)
          .fontSize(12)
      }
    }
  }

  @Builder
  livePhotoButton() {
    SymbolGlyph(this.previewVM.isLivePhoto
      ? $r('sys.symbol.livephoto')
      : $r('sys.symbol.livephoto_slash'))
      .onClick(() => {
        this.previewVM.isLivePhoto = !this.previewVM.isLivePhoto;
        this.previewVM.enableMovingPhoto();
        const message = this.previewVM.isLivePhoto ? $r('app.string.moving_open') : $r('app.string.moving_close');
        showToast(this.getUIContext(), message);
      })
      .fontSize(22)
      .fontColor([AppTheme.TEXT_PRIMARY])
  }

  @Builder
  rateButton() {
    if (this.previewVM.rates) {
      Text(`${this.previewVM.currentRate} fps`)
        .fontColor(AppTheme.TEXT_PRIMARY)
        .fontSize(16)
        .bindMenu(this.previewVM.rates.map(rate => {
          const menuElement: MenuElement = {
            value: rate + 'fps',
            action: () => {
              this.previewVM.setPreviewFrameRate(rate, rate);
              this.previewVM.currentRate = rate;
              showToast(this.getUIContext(), $r('app.string.preview_rate', rate + 'fps'));
            }
          };
          return menuElement;
        }))
    }
  }

  @Builder
  delayPhotoButton(photoDelayTimeElements: MenuElement[]) {
    if (this.previewVM.photoDelayTime) {
      Text(`${this.previewVM.photoDelayTime}s`)
        .fontColor(AppTheme.TEXT_PRIMARY)
        .fontSize(16)
        .bindMenu(photoDelayTimeElements)
    } else {
      SymbolGlyph($r('sys.symbol.time_lapse'))
        .fontSize(22)
        .fontColor([AppTheme.TEXT_PRIMARY])
        .bindMenu(photoDelayTimeElements)
    }
  }

  getPhotoDelayTimeElements(): MenuElement[] {
    const menuTextMap: Map<string, number> = new Map([
      ['off', 0],
      ['2s', 2],
      ['5s', 5],
      ['10s', 10]
    ]);
    return Array.from(menuTextMap.keys()).map(text => {
      const time = menuTextMap.get(text);
      const menuElement: MenuElement = {
        value: text,
        action: () => {
          this.previewVM.photoDelayTime = time!;
          const message = time ? $r('app.string.delay', text) : $r('app.string.delay_close');
          showToast(this.getUIContext(), message);
        }
      };
      return menuElement;
    });
  }

  @Builder
  stabilizationButton() {
    SymbolGlyph(this.previewVM.isStabilizationEnabled
      ? $r('sys.symbol.motion_stabilization')
      : $r('sys.symbol.motion_stabilization_slash'))
      .onClick(async () => {
        this.previewVM.isStabilizationEnabled = !this.previewVM.isStabilizationEnabled;
        this.previewVM.openPreviewBlur();
        await this.previewVM.cameraManagerRelease();
        await this.previewVM.cameraManagerStart();
        this.previewVM.syncButtonSettings();
        const message = this.previewVM.isStabilizationEnabled ? $r('app.string.stabilization_enable') :
          $r('app.string.stabilization_disabled');
        showToast(this.getUIContext(), message);
      })
      .fontSize(22)
      .fontColor([AppTheme.TEXT_PRIMARY])
  }

  build() {
    Row() {
      if (this.previewVM.isPhotoMode()) {
        this.rateButton();
        this.flashButton(this.photoFlashModes);
        this.delayPhotoButton(this.getPhotoDelayTimeElements());
        this.livePhotoButton();
      } else {
        if (this.previewVM.isVideoRecording()) {
          this.videoTimerBuilder();
        } else {
          this.rateButton();
          this.flashButton(this.videoFlashModes);
          this.stabilizationButton();
        }
      }
    }
    .id('settingButtonsView')
    .width('100%')
    .margin({ top: 50 })
    .justifyContent(FlexAlign.SpaceAround)
    .alignRules({ top: { anchor: '__container__', align: VerticalAlign.Top } })
  }
}

export default SettingButtonsView;
